[package]
name = "plagiarism-detector-rust"
version = "1.0.0"
edition = "2021"
publish = false

[workspace]
members = [".", "api", "service", "entity", "migration"]

[dependencies]
plagiarism-detector-rust-api = { path = "api" }
